apiVersion : apps/v1
kind : Deployment
metadata:
  name : platform-deployment
spec : 
  replicas : 1
  selector : 
    matchLabels :
      app : platformservice
  template :
    metadata :
      labels :
        app : platformservice
    spec :
      containers:
        - name : platformservice
          image : praniket01/platformservice:latest

